### ISSUE TITLE
No stable download URL

### ISSUE THREAD

**Issue by Alecaddd** [flathub/io.designer.GravitDesigner#2]
Hello, I can't seem to install Gravit Designer on elementary OS Juno Beta 1, based on Ubuntu 18.04.
Currently running `Flatpak 1.0.1`

This is the error message I get right at the end of the installation process:

```
Installing: io.designer.GravitDesigner/x86_64/stable from flathub
[################### ] Downloading files: 77/77 69.2 MB (2.0 MB/s)              
error: Failed to install io.designer.GravitDesigner/x86_64/stable: Wrong size for extra data https://designer.gravit.io/_downloads/linux/GravitDesigner.zip?v=3.4.3
```

Cheers

**Comment by nedrichards** [comment]
Great, their download URLs aren't stable :-(

Fixed in https://github.com/flathub/io.designer.GravitDesigner/commit/2566a7d02676af9327e95f5c7e4124890b150426

**Comment by alex285** [comment]
hello @nedrichards 
can we re-open this please? im not sure it is fixed 

```
flatpak update io.designer.GravitDesigner

Looking for updates...
Updating in system:
io.designer.GravitDesigner/x86_64/stable flathub 13bcbac11390
Is this ok [y/n]: y
Updating: io.designer.GravitDesigner/x86_64/stable from flathub
[####################] Downloading: 66.5 MB/66.5 MB (773.3 kB/s)               
Error: Failed to update io.designer.GravitDesigner/x86_64/stable: Wrong size for extra data https://designer.gravit.io/_downloads/linux/GravitDesigner.zip?v=3.4.4
```

i noticed another thing. the first time i installed Gravit and worked, i was using Flatpak 1.0.0. That error came only after I upgraded to 1.0.1. Unfortunately im not able at the moment to downgrade to 1.0.0 to re-check if that is the reason

**Comment by aiamuzz** [comment]
same here ... the wrong size error is still occurring !!!

**Comment by nedrichards** [comment]
Fixed again https://github.com/flathub/io.designer.GravitDesigner/commit/f5818dd69e1b2ada60ef23a0a5e658f209217ffa

**Comment by aiamuzz** [comment]
nope ... not fixed ... same error ...

**Comment by nedrichards** [comment]
It will be when this build completes. There's a lot of stuff in the queue. https://flathub.org/builds/#/builders/2/builds/4054

**Comment by nedrichards** [comment]
Apologies, this is moderately distressing insamuch as I seem to be being served a different file

**Comment by nedrichards** [comment]
This build is tracking the file that my VPS is being served rather than my home machine. https://flathub.org/builds/#/builders/2/builds/4062

**Comment by nedrichards** [comment]
in the interim, I'd be interested in users results for wget or curl:
> https://designer.gravit.io/_downloads/linux/GravitDesigner.zip
then
> sha256sum GravitDesigner.zip
and
> ls -l | grep Gravit

**Comment by aiamuzz** [comment]
```
AH15:~/Downloads$ sha256sum GravitDesigner.zip
0f4a5da35c01a2c034037e2accd0a168ebfcfb591e75e187501d3f92beec09bd  GravitDesigner.zip

AH15:~/Downloads$ ls -l | grep Gravit
-rw-r--r-- 1 muz muz   66484097 Aug 30 20:17 GravitDesigner.zip
```

**Comment by nedrichards** [comment]
OK, you're getting what I was getting. Which is strange. Because that appears not to actually work as values. The latest commit is:

```
nick@endless-nedr:~/Projects/io.designer.GravitDesigner$ flatpak info io.designer.GravitDesigner
Ref: app/io.designer.GravitDesigner/x86_64/stable
ID: io.designer.GravitDesigner
Arch: x86_64
Branch: stable
Origin: flathub
Collection ID: org.flathub.Stable
Date: 2018-08-30 15:24:17 +0000
Subject: replace with hash and sha sourced from a different download location (411ab11f)
Commit: e2b785cd574bef902fa96f85906f00ff003b371c9380a5ade493a2f905aa967f
Parent: 9c6da90c0ffc03a9599045ab5fd9f04bd449160741159ad5b350235c8b9a31de
Location: /var/lib/flatpak/app/io.designer.GravitDesigner/x86_64/stable/e2b785cd574bef902fa96f85906f00ff003b371c9380a5ade493a2f905aa967f
Installed size: 13.5 MB
Runtime: org.freedesktop.Platform/x86_64/18.08
Sdk: org.freedesktop.Sdk/x86_64/18.08
```
Which works for me and corresponds to this git commit https://github.com/flathub/io.designer.GravitDesigner/commit/411ab11fe8577522ed337213f5c1d6075e592e5f

**Comment by tstdin** [comment]
```
error: Failed to install io.designer.GravitDesigner/x86_64/stable: Wrong size for extra data https://designer.gravit.io/_downloads/linux/GravitDesigner.zip?v=3.4.4
```

```bash
$ sha256sum GravitDesigner.zip 
e38a4ff3dc14617e864763d5bfce1bb49c80fb611ea53c07a363ef398358826d  GravitDesigner.zip
$ stat -c "%s" GravitDesigner.zip # more accurate way to get file size than from ls -l
66504144
```

**Comment by aiamuzz** [comment]
```
Installing: io.designer.GravitDesigner/x86_64/stable from flathub
[####################] Downloading: 69.8 MB/69.8 MB (812.2 kB/s)               
	error: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256

```

**Comment by cho2** [comment]
```
$ sha256sum GravitDesigner.zip
e38a4ff3dc14617e864763d5bfce1bb49c80fb611ea53c07a363ef398358826d  GravitDesigner.zip

$ ls -l | grep Gravit
-rw-r--r--   1 cho2 users 66504144 Agu 30 06:29 GravitDesigner.zip
```

**Comment by cho2** [comment]
Looks good :thumbsup:
```
$ flatpak install flathub io.designer.GravitDesigner
Memasang: io.designer.GravitDesigner/x86_64/stable dari flathub
[####################] Mengunduh berkas: 1/1 66,5 MB (73,1 kB/s)               
Memasang: io.designer.GravitDesigner.Locale/x86_64/stable dari flathub
[####################] 5 metadata, 1 content objects fetched; 7 KiB transferred in 20 seconds
```

**Comment by aiamuzz** [comment]
strange ... i am still having problems ...

```
Installing: io.designer.GravitDesigner/x86_64/stable from flathub
[####################] Downloading files: 1/1 66.5 MB (1.1 MB/s)                   
error: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256

```

**Comment by nedrichards** [comment]
Yeah, you're getting the version that I was being served this morning it seems! Although how you didn't then install correctly then :-(

**Comment by aiamuzz** [comment]
I had installed it first ... then with the sudo problem i installed it ... ever since installation is running into the problems one after the other listed above ...

BTW ... I am installing using this command ...

`flatpak --installation=myFlatpaks install flathub io.designer.GravitDesigner
`

**Comment by aiamuzz** [comment]
nope ... not for me yet !!!

```
Installing: io.designer.GravitDesigner/x86_64/stable from flathub
[####################] Downloading files: 1/1 66.5 MB (1.0 MB/s)                  
error: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256
```

**Comment by nedrichards** [comment]
@aiamuzz I think you likely have a different issue, possibly to do with running as sudo, which is not recomended.

**Comment by aiamuzz** [comment]
@nedrichards  ... I tried sudo only the first time after it through a permissions error ... i uninstalled the app after that ... ever since its not installing ...

I use the following command to install ... and its failing ...

`flatpak --installation=myFlatpaks install flathub io.designer.GravitDesigner`

**Comment by terndrup** [comment]
Still happening as of September 26th

**Comment by eszlari** [comment]
Fixed again: https://github.com/flathub/io.designer.GravitDesigner/commit/f56543346e192cb5b5f10af50e665246738248b8

@alex285 Maybe you can bug them through twitter till they provide a stable download URL?!

**Comment by alex285** [comment]
@eszlari im not very optimistic it will work, but i tried :)
https://twitter.com/BabyWogue/status/1045053695761813505

**Comment by alex285** [comment]
hello @eszlari @nedrichards 
just to update you that GravitDesigner answered on Twitter that it is not possible on the moment to keep stable download links. Not sure why they didnt contact on here

**Comment by terndrup** [comment]
Works for me now, guess it depends on Mirror stability

**Comment by cho2** [comment]
still error while updating

```
flatpak update
Mencari pembaruan...

Updating in system:
io.designer.GravitDesigner/x86_64/stable flathub 673c440af0d3
Is this ok [y/n]: y
Memperbarui: io.designer.GravitDesigner/x86_64/stable dari flathub
[####################] Mengunduh: 138,0 MB/138,0 MB (143,6 kB/s)           
Galat: Gagal untuk pembaruan io.designer.GravitDesigner/x86_64/stable: Ukuran yang salah untuk data ekstra https://designer.gravit.io/_downloads/linux/GravitDesigner.zip
galat: There were one or more errors
```

**Comment by evenreven** [comment]
@cho2 That's because of this commit which updated the package version: https://github.com/flathub/io.designer.GravitDesigner/commit/b070e0a7fb3268e060a90e90da19abcebdbcac69

Sadly, the GravitDesigner flatpak will break every time Gravit updates their application since they don't use version numbers in their URLs. Oh well, at least the installed package itself doesn't break, it just tries to update and fails. I can live with it.

**Comment by ujnana** [comment]
i am still having problems

```
flatpak install flathub io.designer.GravitDesigner
Installing in system:
io.designer.GravitDesigner/x86_64/stable        flathub 71a99ac43a1d
  permissions: ipc, network, x11, dri
  file access: home
  tags: proprietary
io.designer.GravitDesigner.Locale/x86_64/stable flathub e8905641e9d4
Is this ok [y/n]: y
Installing: io.designer.GravitDesigner/x86_64/stable from flathub
[####################] Downloading files: 1/1 138,0 MB (2,1 MB/s)          
error: Failed to install io.designer.GravitDesigner/x86_64/stable: Wrong size for extra data https://designer.gravit.io/_downloads/linux/GravitDesigner.zip
```

**Comment by eszlari** [comment]
I fixed it again: https://github.com/flathub/io.designer.GravitDesigner/commit/368aa82baf6a9ea06097252395a7208d416ae8e4

If you want to get this fixed permanently, ask Gravit for a stable download URL:

https://discuss.gravit.io

**Comment by healBvdb** [comment]
Hi eszlari. The flatpak install is down again. Can we fit it in the repo for you ?

**Comment by eszlari** [comment]
updated to 2019-1.9: https://github.com/flathub/io.designer.GravitDesigner/commit/57342637bd75645960b85f132844cfb76c0f112f

**Comment by HannanAkbar** [comment]
https://github.com/flathub/io.designer.GravitDesigner/pull/13 Update to 3.5.26 2019-08-21

**Comment by yaomtc** [comment]
Also having this issue here.

I've created the request, as suggested last year. 

https://discuss.gravit.io/t/stable-download-url/10958

**Comment by Hermitter** [comment]
Is there any fix for this issue yet?

Installation error:
```Wrong size for extra data https://designer.gravit.io/_downloads/linux/-GravitDesigner.zip```

**Comment by yaomtc** [comment]
Please post a comment on that request I linked.

We can't fix the issue, we just have to wait for eszlari to update the installer, or for Corel to start using versioned releases or something.

**Comment by TingPing** [comment]
Anybody can feel free to update the information here: https://github.com/flathub/io.designer.GravitDesigner/blob/bb824c1df77e804b4caba0f02be10f4543168e5a/io.designer.GravitDesigner.yaml#L51-L52

In a PR and I'll gladly merge it whenever an update happens.

**Comment by yaomtc** [comment]
Done. (Oddly, the ZIP is now less than half the size it was before. Wonder what they changed.)

Also, I reached out to the Gravit team via the contact form about having a stable download URL.

> thanks for reaching out to Gravit.
> 
> Thanks for your suggestion but I've checked with our product manager and I'm afraid we don't have plans to change that. 
> 
> I'm sorry.
> 
> Please let me know if there is anything else I can do.

**Comment by eszlari** [comment]
@FakeShemp Why did you close this?

**Comment by FakeShemp** [comment]
By accident

**Comment by thiagolucio** [comment]
Same here.
 
OS: Fedora x86_64
Model: Latitude 3400 
Kernel: 5.10.15-200.fc33.x86_64 
Shell: /bin/bash 5.0.17 
CPU: Intel i5-8265U (8) @ 3.900GHz [55.0°on] 
CPU Usage: 14% 
Memory: 3738MiB / 15872MiB 
GPU: Intel WhiskeyLake-U GT2 [UHD Graphics 620] 
Resolution: 2560x1080 

![gravit](https://user-images.githubusercontent.com/5756266/108062531-ae51ad80-7038-11eb-8034-f2db8f6b3a6f.png)

**Comment by TjayNL** [comment]
Still getting this error after trying to install it via flathub:

Error: Invalid checksum for extra data https://designer.gravit.io/_downloads/linux/GravitDesigner.zip
error: Failed to install io.designer.GravitDesigner: Invalid checksum for extra data https://designer.gravit.io/_downloads/linux/GravitDesigner.zip

**Comment by thiagolucio** [comment]
> Done. (Oddly, the ZIP is now less than half the size it was before. Wonder what they changed.)
> 
> Also, I reached out to the Gravit team via the contact form about having a stable download URL.
> 
> > thanks for reaching out to Gravit.
> > Thanks for your suggestion but I've checked with our product manager and I'm afraid we don't have plans to change that.
> > I'm sorry.
> > Please let me know if there is anything else I can do.

This is bad. I think that this problem cannot be solved. I think it is a reflection of the Corel sales team. Sad for this sale.

**Comment by smcv** [comment]
According to flatpak/flatpak#4272, the referenced file has changed again.

**Comment by tjaynl** [comment]
Getting an error again:

```
Error: Wrong size for extra data https://designer.gravit.io/_downloads/linux/GravitDesigner.zip
error: Failed to install io.designer.GravitDesigner: Wrong size for extra data https://designer.gravit.io/_downloads/linux/GravitDesigner.zip
```

**Comment by Sush-ruta** [comment]
Same error:
```
Error: Wrong size for extra data https://designer.gravit.io/_downloads/linux/GravitDesigner.zip
error: Failed to install io.designer.GravitDesigner: Wrong size for extra data https://designer.gravit.io/_downloads/linux/GravitDesigner.zip
```

OS: Ubuntu 21.10
Flatpak version: 1.10.2

**Comment by kalligator** [comment]
> Anybody can feel free to update the information here:
>
>https://github.com/flathub/io.designer.GravitDesigner/blob/bb824c1df77e804b4caba0f02be10f4543168e5a/io.designer.GravitDesigner.yaml#L51-L52
> 
> In a PR and I'll gladly merge it whenever an update happens.

I just pushed one a moment ago. 
I just installed it successfully using the link given by the buildbot `flatpak install https://dl.flathub.org/build-repo/98864/io.designer.GravitDesigner.flatpakref`
